### ISSUE TITLE
Cannot make  

### ISSUE THREAD

**Issue by maomran** [ysshao/LLVM-Tracer#26]
- I had to modify CMakefiles, I commented out `find_package(ZLIB)` and manually set ZLIB `lib` and `include` dirs since I installed them from sources. 
- cmake configuration is complete. 
- when I try to `make` I get this error: 
`/data/omran/emerald/llvm_install/bin/llvm-link: /data/omran/emerald/LLVM-Tracer/build/profile-func/trace_logger.obj.llvm:1:1: error: expected top-level entity`

**Comment by rgly** [comment]
You don't have to modify the machine-generated CMakefiles in order to add a library path.
Please use `cmake /where/llvm-tracer/ -DCMAKE_PREFIX_PATH="/where/zlib/install"` to make cmake search zlib on the specified path.
[https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html](https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html)

And I have no idea how `expected top-level entity` comes, could you please `make VERBOSE=1` to see compilation details?

**Comment by maomran** [comment]
That worked fine, thanks
