### ISSUE TITLE
full_trace.cpp:1:10: fatal error: 'vector' file not found

### ISSUE THREAD

**Issue by andrestoga** [ysshao/LLVM-Tracer#7]
Hi,

I got the following error trying to make full-trace:

full_trace.cpp:1:10: fatal error: 'vector' file not found
# include <vector>

```
     ^
```

Can you help me please?

Best,

**Comment by ysshao** [comment]
Hi andrestoga, 

This is because that clang can't find the c++ headers. Can you do a

which gcc

on your machine and then set GCC_INSTALL_HOME to be:

export GCC_INSTALL_HOME=/path/to/your/gcc-4.7-or-up/installation

For example, if your gcc is at /usr/local/bin/gcc, then set your GCC_INSTALL_HOME to be /usr/local/.

Let me know whether it works. 

Thanks,
Sophia

**Comment by andrestoga** [comment]
Hi Sophia,

Thanks for your answer!

It worked, I set GCC_INSTALL_HOME as a /usr/local/bin instead as a /usr/local

Thanks for your help. Now I have another problem regarding running the example. I'm gonna create another thread for that.

Thanks!

Best,
